[package]
name = "raytrace"
version = "0.1.0"
authors = ["Nick Yu <n.j.k.yu@student.tudelft.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.6"
cgmath = "0.17.0"
rand = "0.7.3"